export default [
    // ==========================================
    // BASE GAME - LAWS
    // ==========================================
    {
        id: 'anti_intellectual_revolution',
        name: 'Anti-Intellectual Revolution',
        type: 'law',
        electType: 'for_against',
        forEffect: 'After a player researches a technology, they must destroy 1 of their non-fighter ships.',
        againstEffect: 'At the start of the next strategy phase, each player exhausts 1 planet for each technology they own.',
        electedEffect: null,
        expansionId: 'base',
    },
    {
        id: 'classified_document_leaks',
        name: 'Classified Document Leaks',
        type: 'law',
        electType: 'scored_secret',
        forEffect: null,
        againstEffect: null,
        electedEffect: 'The elected secret objective becomes a public objective; place it near the other public objectives.',
        expansionId: 'base',
    },
    {
        id: 'committee_formation',
        name: 'Committee Formation',
        type: 'law',
        electType: 'player',
        forEffect: null,
        againstEffect: null,
        electedEffect:
            'The elected player gains this card. Before players vote on an agenda that requires a player to be elected, the owner of this card may discard this card to choose a player to be elected. Players do not vote on that agenda.',
        expansionId: 'base',
    },
    {
        id: 'conventions_of_war',
        name: 'Conventions of War',
        type: 'law',
        electType: 'for_against',
        forEffect: 'Players cannot use BOMBARDMENT against units that are on cultural planets.',
        againstEffect: 'Each player that voted Against discards all of their action cards.',
        expansionId: 'base',
    },
    {
        id: 'core_mining',
        name: 'Core Mining',
        type: 'law',
        electType: 'hazardous_planet',
        forEffect: null,
        againstEffect: null,
        electedEffect: "Attach this card to the elected planet's card. Then, destroy 1 infantry on the planet. The resource value of this planet is increased by 2.",
        expansionId: 'base',
        removedInExpansionId: 'pok',
    },
    {
        id: 'demilitarized_zone',
        name: 'Demilitarized Zone',
        type: 'law',
        electType: 'cultural_planet',
        forEffect: null,
        againstEffect: null,
        electedEffect:
            "Attach this card to the elected planet's card. Then, destroy all units on that planet. Players' units cannot land, be produced, or be placed on this planet.",
        expansionId: 'base',
        removedInExpansionId: 'pok',
    },
    {
        id: 'enforced_travel_ban',
        name: 'Enforced Travel Ban',
        type: 'law',
        electType: 'for_against',
        forEffect: 'Alpha and beta wormholes have no effect during movement.',
        againstEffect: 'Destroy each PDS in or adjacent to a system that contains a wormhole.',
        expansionId: 'base',
    },
    {
        id: 'executive_sanctions',
        name: 'Executive Sanctions',
        type: 'law',
        electType: 'for_against',
        forEffect: 'Each player can have a maximum of 3 action cards in their hand.',
        againstEffect: 'Each player discards 1 random action card from their hand.',
        expansionId: 'base',
    },
    {
        id: 'fleet_regulations',
        name: 'Fleet Regulations',
        type: 'law',
        electType: 'for_against',
        forEffect: 'Each player cannot have more than 4 tokens in their fleet pool.',
        againstEffect: 'Each player places 1 command token from their reinforcements in their fleet pool.',
        expansionId: 'base',
    },
    {
        id: 'holy_planet_of_ixth',
        name: 'Holy Planet of Ixth',
        type: 'law',
        electType: 'cultural_planet',
        forEffect: null,
        againstEffect: null,
        electedEffect:
            "Attach this card to the elected planet's card. The planet's owner gains 1 victory point. Units on this planet cannot use PRODUCTION. When a player gains control of this planet, they gain 1 victory point. When a player loses control of this planet, they lose 1 victory point.",
        expansionId: 'base',
        removedInExpansionId: 'pok',
    },
    {
        id: 'homeland_defense_act',
        name: 'Homeland Defense Act',
        type: 'law',
        electType: 'for_against',
        forEffect: 'Each player can have any number of PDS units on planets they control in their home system.',
        againstEffect: 'Each player destroys 1 of their PDS units.',
        expansionId: 'base',
    },
    {
        id: 'imperial_arbiter',
        name: 'Imperial Arbiter',
        type: 'law',
        electType: 'player',
        forEffect: null,
        againstEffect: null,
        electedEffect:
            "The elected player gains this card. At any time, the owner of this card may discard this card to swap 1 of their strategy cards with 1 of another player's strategy cards.",
        expansionId: 'base',
    },
    {
        id: 'minister_of_commerce',
        name: 'Minister of Commerce',
        type: 'law',
        electType: 'player',
        forEffect: null,
        againstEffect: null,
        electedEffect: 'The elected player gains this card. After the owner of this card replenishes commodities, they gain 1 trade good for each player that is their neighbor.',
        expansionId: 'base',
    },
    {
        id: 'minister_of_exploration',
        name: 'Minister of Exploration',
        type: 'law',
        electType: 'player',
        forEffect: null,
        againstEffect: null,
        electedEffect: 'The elected player gains this card. When the owner of this card gains control of a planet, they gain 1 trade good.',
        expansionId: 'base',
    },
    {
        id: 'minister_of_industry',
        name: 'Minister of Industry',
        type: 'law',
        electType: 'player',
        forEffect: null,
        againstEffect: null,
        electedEffect:
            'The elected player gains this card. When the owner of this card places a space dock in a system, their units in that system may use their PRODUCTION abilities.',
        expansionId: 'base',
    },
    {
        id: 'minister_of_peace',
        name: 'Minister of Peace',
        type: 'law',
        electType: 'player',
        forEffect: null,
        againstEffect: null,
        electedEffect:
            "The elected player gains this card. After a player activates a system that contains 1 or more of a different player's units, the owner of this card may discard this card; immediately end the active player's turn.",
        expansionId: 'base',
    },
    {
        id: 'minister_of_policy',
        name: 'Minister of Policy',
        type: 'law',
        electType: 'player',
        forEffect: null,
        againstEffect: null,
        electedEffect: 'The elected player gains this card. At the end of the status phase, the owner of this card draws 1 action card.',
        expansionId: 'base',
    },
    {
        id: 'minister_of_sciences',
        name: 'Minister of Sciences',
        type: 'law',
        electType: 'player',
        forEffect: null,
        againstEffect: null,
        electedEffect:
            'The elected player gains this card. When the owner of this card resolves the primary or secondary ability of the Technology strategy card, they do not need to spend resources to research technology.',
        expansionId: 'base',
    },
    {
        id: 'minister_of_war',
        name: 'Minister of War',
        type: 'law',
        electType: 'player',
        forEffect: null,
        againstEffect: null,
        electedEffect:
            'The elected player gains this card. The owner of this card may discard this card after performing an action to remove 1 of their command counters from the game board and return it to their reinforcements; then they may perform 1 additional action.',
        expansionId: 'base',
    },
    {
        id: 'prophecy_of_ixth',
        name: 'Prophecy of Ixth',
        type: 'law',
        electType: 'player',
        forEffect: null,
        againstEffect: null,
        electedEffect:
            "The elected player gains this card. The owner of this card applies +1 to the result of their fighter's combat rolls. When the owner of this card uses PRODUCTION, they discard this card unless they produce 2 or more fighters.",
        expansionId: 'base',
    },
    {
        id: 'publicize_weapon_schematics',
        name: 'Publicize Weapon Schematics',
        type: 'law',
        electType: 'for_against',
        forEffect: 'If any player owns a war sun technology, all players may ignore all prerequisites on war sun technologies. All war suns lose SUSTAIN DAMAGE.',
        againstEffect: 'Each player that owns a war sun technology discards all of their action cards.',
        expansionId: 'base',
    },
    {
        id: 'regulated_conscription',
        name: 'Regulated Conscription',
        type: 'law',
        electType: 'for_against',
        forEffect: 'When a player produces units, they produce only 1 fighter and infantry for its cost instead of 2.',
        againstEffect: 'No effect.',
        expansionId: 'base',
    },
    {
        id: 'representative_government',
        name: 'Representative Government',
        type: 'law',
        electType: 'for_against',
        forEffect: 'Players cannot exhaust planets to cast votes during the agenda phase. Each player may cast 1 vote on each agenda instead.',
        againstEffect: 'At the start of the next strategy phase, each player that voted Against exhausts all of their cultural planets.',
        expansionId: 'base',
        removedInExpansionId: 'pok',
        replacedById: 'representative_government_pok',
    },
    {
        id: 'research_team_biotic',
        name: 'Research Team: Biotic',
        type: 'law',
        electType: 'industrial_planet',
        forEffect: null,
        againstEffect: null,
        electedEffect:
            "Attach this card to the elected planet's card. When the owner of this planet researches technology, they may exhaust this card to ignore 1 green prerequisite.",
        expansionId: 'base',
        removedInExpansionId: 'pok',
    },
    {
        id: 'research_team_cybernetic',
        name: 'Research Team: Cybernetic',
        type: 'law',
        electType: 'industrial_planet',
        forEffect: null,
        againstEffect: null,
        electedEffect:
            "Attach this card to the elected planet's card. When the owner of this planet researches technology, they may exhaust this card to ignore 1 yellow prerequisite.",
        expansionId: 'base',
        removedInExpansionId: 'pok',
    },
    {
        id: 'research_team_propulsion',
        name: 'Research Team: Propulsion',
        type: 'law',
        electType: 'industrial_planet',
        forEffect: null,
        againstEffect: null,
        electedEffect:
            "Attach this card to the elected planet's card. When the owner of this planet researches technology, they may exhaust this card to ignore 1 blue prerequisite.",
        expansionId: 'base',
        removedInExpansionId: 'pok',
    },
    {
        id: 'research_team_warfare',
        name: 'Research Team: Warfare',
        type: 'law',
        electType: 'hazardous_planet',
        forEffect: null,
        againstEffect: null,
        electedEffect:
            "Attach this card to the elected planet's card. When the owner of this planet researches technology, they may exhaust this card to ignore 1 red prerequisite.",
        expansionId: 'base',
        removedInExpansionId: 'pok',
    },
    {
        id: 'senate_sanctuary',
        name: 'Senate Sanctuary',
        type: 'law',
        electType: 'cultural_planet',
        forEffect: null,
        againstEffect: null,
        electedEffect: "Attach this card to the elected planet's card. The influence value of this planet is increased by 2.",
        expansionId: 'base',
        removedInExpansionId: 'pok',
    },
    {
        id: 'shard_of_the_throne',
        name: 'Shard of the Throne',
        type: 'law',
        electType: 'player',
        forEffect: null,
        againstEffect: null,
        electedEffect:
            'The elected player gains this card and 1 victory point. A player gains this card and 1 victory point when they win a combat against the owner of this card. Then, the previous owner of this card loses 1 victory point.',
        expansionId: 'base',
        removedInExpansionId: 'pok',
    },
    {
        id: 'shared_research',
        name: 'Shared Research',
        type: 'law',
        electType: 'for_against',
        forEffect: "Each player's units can move through nebulae.",
        againstEffect: 'Each player places a command token from their reinforcements in their home system, if able.',
        expansionId: 'base',
    },
    {
        id: 'terraforming_initiative',
        name: 'Terraforming Initiative',
        type: 'law',
        electType: 'hazardous_planet',
        forEffect: null,
        againstEffect: null,
        electedEffect: "Attach this card to the elected planet's card. The resource and influence values of this planet are each increased by 1.",
        expansionId: 'base',
        removedInExpansionId: 'pok',
    },
    {
        id: 'the_crown_of_emphidia',
        name: 'The Crown of Emphidia',
        type: 'law',
        electType: 'player',
        forEffect: null,
        againstEffect: null,
        electedEffect:
            "The elected player gains this card and 1 victory point. A player gains this card and 1 victory point after they gain control of a planet in the home system of this card's owner. Then, the previous owner of this card loses 1 victory point.",
        expansionId: 'base',
        removedInExpansionId: 'pok',
    },
    {
        id: 'the_crown_of_thalnos',
        name: 'The Crown of Thalnos',
        type: 'law',
        electType: 'player',
        forEffect: null,
        againstEffect: null,
        electedEffect:
            'The elected player gains this card. During each combat round, the owner of this card may reroll any number of dice; they must destroy each of their units that did not produce a hit with its reroll.',
        expansionId: 'base',
        removedInExpansionId: 'pok',
    },
    {
        id: 'wormhole_reconstruction',
        name: 'Wormhole Reconstruction',
        type: 'law',
        electType: 'for_against',
        forEffect: 'All systems that contain either an alpha or beta wormhole are adjacent to each other.',
        againstEffect: 'Each player places a command token from their reinforcements in each system that contains a wormhole and 1 or more of their ships.',
        expansionId: 'base',
    },

    // ==========================================
    // BASE GAME - DIRECTIVES
    // ==========================================
    {
        id: 'archived_secret',
        name: 'Archived Secret',
        type: 'directive',
        electType: 'player',
        forEffect: null,
        againstEffect: null,
        electedEffect: 'The elected player draws 1 secret objective.',
        expansionId: 'base',
    },
    {
        id: 'arms_reduction',
        name: 'Arms Reduction',
        type: 'directive',
        electType: 'for_against',
        forEffect: 'Each player destroys all but 2 of their dreadnoughts and all but 4 of their cruisers.',
        againstEffect: 'At the start of the next strategy phase, each player exhausts each of their planets that have a technology specialty.',
        expansionId: 'base',
    },
    {
        id: 'colonial_redistribution',
        name: 'Colonial Redistribution',
        type: 'directive',
        electType: 'non_home_non_mecatol',
        forEffect: null,
        againstEffect: null,
        electedEffect:
            'Destroy each unit on the elected planet. Then, the player who controls that planet chooses 1 player with the fewest victory points; that player may place 1 infantry from their reinforcements on the elected planet.',
        expansionId: 'base',
    },
    {
        id: 'compensated_disarmament',
        name: 'Compensated Disarmament',
        type: 'directive',
        electType: 'planet',
        forEffect: null,
        againstEffect: null,
        electedEffect: 'Destroy each ground force on the elected planet; for each unit that was destroyed, the player who controls that planet gains 1 trade good.',
        expansionId: 'base',
    },
    {
        id: 'economic_equality',
        name: 'Economic Equality',
        type: 'directive',
        electType: 'for_against',
        forEffect: 'Each player returns all of their trade goods to the supply. Then, each player gains 5 trade goods.',
        againstEffect: 'Each player returns all of their trade goods to the supply.',
        expansionId: 'base',
    },
    {
        id: 'incentive_program',
        name: 'Incentive Program',
        type: 'directive',
        electType: 'for_against',
        forEffect: 'Draw and reveal 1 stage I public objective from the deck and place it near the public objectives.',
        againstEffect: 'Draw and reveal 1 stage II public objective from the deck and place it near the public objectives.',
        expansionId: 'base',
    },
    {
        id: 'ixthian_artifact',
        name: 'Ixthian Artifact',
        type: 'directive',
        electType: 'for_against',
        forEffect:
            "The speaker rolls 1 die. If the result is 6-10, each player may research 2 technologies. If the result is 1-5, destroy all units in Mecatol Rex's system, and each player with units in systems adjacent to Mecatol Rex's system destroys 3 of their units in each of those systems.",
        againstEffect: 'No effect.',
        expansionId: 'base',
    },
    {
        id: 'judicial_abolishment',
        name: 'Judicial Abolishment',
        type: 'directive',
        electType: 'law',
        forEffect: null,
        againstEffect: null,
        electedEffect: 'Discard the elected law from play.',
        expansionId: 'base',
    },
    {
        id: 'miscount_disclosed',
        name: 'Miscount Disclosed',
        type: 'directive',
        electType: 'law',
        forEffect: null,
        againstEffect: null,
        electedEffect: 'Vote on the elected law as if it were just revealed from the top of the deck.',
        expansionId: 'base',
    },
    {
        id: 'mutiny',
        name: 'Mutiny',
        type: 'directive',
        electType: 'for_against',
        forEffect: 'Each player who voted For gains 1 victory point.',
        againstEffect: 'Each player who voted For loses 1 victory point.',
        expansionId: 'base',
    },
    {
        id: 'new_constitution',
        name: 'New Constitution',
        type: 'directive',
        electType: 'for_against',
        forEffect: 'Discard all laws in play. At the start of the next strategy phase, each player exhausts each planet in their home system.',
        againstEffect: 'No effect.',
        expansionId: 'base',
    },
    {
        id: 'public_execution',
        name: 'Public Execution',
        type: 'directive',
        electType: 'player',
        forEffect: null,
        againstEffect: null,
        electedEffect:
            'The elected player discards all of their action cards. If they have the speaker token, they give it to the player on their left. The elected player cannot vote on any agendas during this agenda phase.',
        expansionId: 'base',
    },
    {
        id: 'seed_of_an_empire',
        name: 'Seed of an Empire',
        type: 'directive',
        electType: 'for_against',
        forEffect: 'The player with most victory points gains 1 victory point.',
        againstEffect: 'The player with the fewest victory points gains 1 victory point.',
        expansionId: 'base',
    },
    {
        id: 'swords_to_plowshares',
        name: 'Swords to Plowshares',
        type: 'directive',
        electType: 'for_against',
        forEffect:
            'Each player destroys half of their infantry on each planet they control, rounded up. Then, each player gains trade goods equal to the number of their infantry that were destroyed.',
        againstEffect: 'Each player places 1 infantry from their reinforcements on each planet they control.',
        expansionId: 'base',
    },
    {
        id: 'unconventional_measures',
        name: 'Unconventional Measures',
        type: 'directive',
        electType: 'for_against',
        forEffect: 'Each player that voted For draws 2 action cards.',
        againstEffect: 'Each player that voted For discards all of their action cards.',
        expansionId: 'base',
    },
    {
        id: 'wormhole_research',
        name: 'Wormhole Research',
        type: 'directive',
        electType: 'for_against',
        forEffect:
            'Each player who has 1 or more ships in a system that contains a wormhole may research 1 technology. Then, destroy all ships in systems that contain an alpha or beta wormhole.',
        againstEffect: 'Each player that voted Against removes 1 command token from their command sheet and returns it to their reinforcements.',
        expansionId: 'base',
    },

    // ==========================================
    // PROPHECY OF KINGS - LAWS
    // ==========================================
    {
        id: 'articles_of_war',
        name: 'Articles of War',
        type: 'law',
        electType: 'for_against',
        forEffect: 'All mechs lose their printed abilities except for SUSTAIN DAMAGE.',
        againstEffect: 'Each player that voted For gains 3 trade goods.',
        expansionId: 'pok',
    },
    {
        id: 'representative_government_pok',
        name: 'Representative Government',
        type: 'law',
        electType: 'for_against',
        forEffect:
            'Players cannot exhaust planets to cast votes during the agenda phase; each player may cast 1 vote on each agenda instead. Players cannot cast additional votes.',
        againstEffect: 'At the start of the next strategy phase, each player that voted Against exhausts all of their cultural planets.',
        expansionId: 'pok',
    },
    {
        id: 'checks_and_balances',
        name: 'Checks and Balances',
        type: 'law',
        electType: 'for_against',
        forEffect:
            'When a player chooses a strategy card during the strategy phase, they give that strategy card to another player that does not have 1 (or a player that does not have 2 in a three- or four-player game), if able.',
        againstEffect: 'Each player readies only 3 of their planets at the end of this agenda phase.',
        expansionId: 'pok',
    },
    {
        id: 'nexus_sovereignty',
        name: 'Nexus Sovereignty',
        type: 'law',
        electType: 'for_against',
        forEffect: 'Alpha and beta wormholes in the wormhole nexus have no effect during movement.',
        againstEffect: 'Place a gamma wormhole token in the Mecatol Rex system.',
        expansionId: 'pok',
    },
    {
        id: 'political_censure',
        name: 'Political Censure',
        type: 'law',
        electType: 'player',
        forEffect: null,
        againstEffect: null,
        electedEffect:
            'The elected player gains this card and 1 victory point. The elected player cannot play action cards. If the owner of this card loses this card, they lose 1 victory point.',
        expansionId: 'pok',
    },
    {
        id: 'search_warrant',
        name: 'Search Warrant',
        type: 'law',
        electType: 'player',
        forEffect: null,
        againstEffect: null,
        electedEffect: 'The elected player gains this card and draws 2 secret objectives. The owner of this card plays with their secret objectives revealed.',
        expansionId: 'pok',
    },

    // ==========================================
    // PROPHECY OF KINGS - DIRECTIVES
    // ==========================================
    {
        id: 'armed_forces_standardization',
        name: 'Armed Forces Standardization',
        type: 'directive',
        electType: 'player',
        forEffect: null,
        againstEffect: null,
        electedEffect:
            'The elected player places command tokens from their reinforcements so that they have 3 tokens in their tactic pool, 3 tokens in their fleet pool, and 2 tokens in their strategy pool. They return any excess tokens to their reinforcements.',
        expansionId: 'pok',
    },
    {
        id: 'clandestine_operations',
        name: 'Clandestine Operations',
        type: 'directive',
        electType: 'for_against',
        forEffect: 'Each player removes 2 command tokens from their command sheet and returns those tokens to their reinforcements.',
        againstEffect: 'Each player removes 1 command token from their fleet pool and returns that token to their reinforcements.',
        expansionId: 'pok',
    },
    {
        id: 'covert_legislation',
        name: 'Covert Legislation',
        type: 'directive',
        electType: 'covert',
        forEffect: null,
        againstEffect: null,
        electedEffect:
            'The speaker draws the next card from the agenda deck but does not reveal it to the other players. Instead, the speaker reads the eligible outcomes aloud; the other players vote for these outcomes as if they were outcomes of this agenda, without knowing their effects.',
        expansionId: 'pok',
    },
    {
        id: 'galactic_crisis_pact',
        name: 'Galactic Crisis Pact',
        type: 'directive',
        electType: 'strategy_card',
        forEffect: null,
        againstEffect: null,
        electedEffect:
            "Each player may perform the secondary ability of the elected strategy card without spending a command token; command tokens placed by the ability are placed from a player's reinforcements instead.",
        expansionId: 'pok',
    },
    {
        id: 'minister_of_antiques',
        name: 'Minister of Antiques',
        type: 'directive',
        electType: 'player',
        forEffect: null,
        againstEffect: null,
        electedEffect: 'The elected player gains 1 relic.',
        expansionId: 'pok',
    },
    {
        id: 'rearmament_agreement',
        name: 'Rearmament Agreement',
        type: 'directive',
        electType: 'for_against',
        forEffect: 'Each player places 1 mech from their reinforcements on a planet they control in their home system.',
        againstEffect: 'Each player replaces each of their mechs with 1 infantry from their reinforcements.',
        expansionId: 'pok',
    },
    {
        id: 'research_grant_reallocation',
        name: 'Research Grant Reallocation',
        type: 'directive',
        electType: 'player',
        forEffect: null,
        againstEffect: null,
        electedEffect:
            'The elected player gains any 1 technology of their choice. Then, for each prerequisite on that technology, they remove 1 token from their fleet pool and return it to their reinforcements.',
        expansionId: 'pok',
    },
];
